import time

from discord.ext import commands
import util


class Channel(commands.Cog, name="頻道管理"):
    def __init__(self, bot):
        self.bot = bot

    @commands.command()
    @commands.is_owner()
    async def backup(self, ctx, *args):
        """備份文字頻道

        使用範例：
        backup
        backup <channel_id>
        """
        if not args:
            channel = ctx.channel
        else:
            channel = self.bot.get_channel(int(args[0]))

        if channel is None:
            await ctx.send("找不到頻道")
            return

        await ctx.send("開始備份頻道：{}".format(channel.name))
        output_messages = []
        previous_author = None
        async for message in channel.history(limit=None, oldest_first=True):
            if message.author != previous_author:
                # display author name only if author changed
                output_messages.append("")
                output_messages.append(message.author.display_name + ":")
                previous_author = message.author
            output_messages.append(message.content)

        # upload content to gist
        gist_url = util.create_gist(
            filename=channel.name,
            description="generated by discord bot at {}".format(time.strftime('%Y-%m-%d %H:%M:%S')),
            content="\n".join(output_messages)
        )
        await ctx.send("備份完成：{}".format(gist_url))
